version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_exports:/app/exports
    environment:
      - DATABASE_URL=wsjf.db
      - ALLOWED_HOSTS=["http://localhost:3000"]
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000

  db:
    image: alpine:latest
    volumes:
      - db_data:/data
    command: /bin/sh -c "while true; do sleep 30; done"

volumes:
  db_data:
  backend_exports: